spring.application.name=api-gateway
server.port=8091

management.tracing.enabled=true
management.tracing.sampling.probability=1.0
spring.cloud.gateway.server.webflux.metrics.enabled=true
management.observations.annotations.enabled=true
spring.cloud.gateway.server.webflux.httpclient.observation.enabled=true

#Rate limiting
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cloud.gateway.server.webflux.routes[0].id=notification-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/notification/**
#Rate limiting
spring.cloud.gateway.server.webflux.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.replenishRate=15
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=30
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.requestedTokens=1
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.key-resolver=#{@userKeyResolver}

spring.cloud.gateway.server.webflux.routes[1].id=logging-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/logging/**
#Rate limiting
spring.cloud.gateway.server.webflux.routes[1].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.redis-rate-limiter.replenishRate=30
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.redis-rate-limiter.burstCapacity=60
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.redis-rate-limiter.requestedTokens=1
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.key-resolver=#{@userKeyResolver}

spring.cloud.gateway.server.webflux.routes[2].id=nebula-api
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8087
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/**
#Rate limiting
spring.cloud.gateway.server.webflux.routes[2].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.redis-rate-limiter.replenishRate=30
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.redis-rate-limiter.burstCapacity=60
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.redis-rate-limiter.requestedTokens=1
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.key-resolver=#{@userKeyResolver}

spring.cloud.gateway.server.webflux.routes[3].id=nebula-auth
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8090
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/auth/**
#Rate limiting
spring.cloud.gateway.server.webflux.routes[3].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[3].filters[0].args.redis-rate-limiter.replenishRate=30
spring.cloud.gateway.server.webflux.routes[3].filters[0].args.redis-rate-limiter.burstCapacity=60
spring.cloud.gateway.server.webflux.routes[3].filters[0].args.redis-rate-limiter.requestedTokens=1
spring.cloud.gateway.server.webflux.routes[3].filters[0].args.key-resolver=#{@userKeyResolver}